### ISSUE TITLE
Recompile Issue after Cloning in VS

### ISSUE THREAD

**Issue by XavierT31830** [drok/NetworkExtensions3#10]
I can't recompile the project in VS, i wanted to make personal translations for me and recompile the project in VS but i can't or maybe i don't know how... (i am just starting to learn and understand coding and its tools like VS and VS code)

So, i open the "Network Extensions 3.sln" and i have this error message :
![Message d'erreur](https://user-images.githubusercontent.com/28814440/152651709-fe1cc1d1-4de2-464e-8ce7-988082654225.png)

Then, into VS it looks like this :
![Affichage VS](https://user-images.githubusercontent.com/28814440/152651959-578f858d-494e-4ee5-b6af-a9c9942c77ea.png)

The error messages are :
C:\Users\Mamy la Puce\Desktop\Cours Velum\Test DLL\- UPDATE_NetworkExtensions3\ObjUnity3D\ObjUnity3D.csproj : error  : impossible d'évaluer l'expression "[MSBuild]::NormalizeDirectory('')". La longueur du paramètre "path" ne peut pas être égale à zéro.  C:\Users\Mamy la Puce\Desktop\Cours Velum\Test DLL\- UPDATE_NetworkExtensions3\CitySkylinesPath.props

Same message for all the nine .csproj : 

ObjUnity3D.csproj
Transit.Addon.csproj
Transit.Addon.PathFinding.csproj
Transit.Addon.RoadExtensions.csproj
Transit.Addon.Tools.csproj
Transit.Framework.csproj
Transit.Framework.ExtensionPoints.csproj
Transit.Framework.Hooks.csproj
Transit.Framework.Redirection.csproj

Maybe the solution is simple... and I'll probably look like an idiot but that's okay, I would have asked ^^

**Comment by drok** [comment]
Thank you for the bug report. I pushed the fix to master.

This error was due to Unity not being installed, and the project setup assuming it was. Unity is only needed in Debug configuration to generate *.mdb symbol files.

The project will now correctly detect Unity, and ignore it in Release mode, or error out with instructions to install Unity in Debug mode.
